### ISSUE TITLE
Ei lase kontakti salvestada 

### ISSUE THREAD

**Issue by hnagel413** [Eggii/PhoneBook#1]
Kontakti ei lase salvestada kui zip koodi on muudetud. Isegi olemas oleva koodi puhul teavitab, et ei sobi.

Kontakti loomine:
![originaal](https://user-images.githubusercontent.com/31770163/48027151-a5cb5680-e150-11e8-879f-25a53455d09c.png)

Zip koodi muutmine:
![uus](https://user-images.githubusercontent.com/31770163/48027176-b8459000-e150-11e8-9318-8dd1470abab1.png)

**Comment by Eggii** [comment]
Kuna valideerimise meetodit ei olnud ette seatud, siis selline suunakood(6300 Broager) peabki andma veateate, kuna sellist suunakoodi ei ole selles andmebaasis, sest suunakood ei sobi linna nimega. 6300 suunakoodile vastab linn niimega Gråsten.

Minu lahenduses peab olema suunakood kooskõlas linna nimega mis on varem sisestatud andmebaasi.
Sobib ka ainult suunakoodi number, sellisel juhul lisab kood ise suunakoodile õige linna nime.

Salvestamisel tekkis probleem, kuna ei olnud ära vahetatud muutuja nime mis salvestaks uue suunakoodi. Nüüd salvestab programm ka uue suunakoodi.
